### PR TITLE
js13kpwa tweaks

### PR DESCRIPTION
**Pull request by mohawk2**

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Hi @mohawk2. I appreciate the effort here, but I'm not going to accept this PR for two reasons:

1. When learning something, the most concise code is not always the best code. I agree that the `map()` method deals with this concisely, but it is also harder to see what is going on.
2. You _do_ need the bits of path information that you were deleting — SW files a referenced relative to the base URL of the location, not the calling file.

**Comment by mohawk2** [comment]
It's your trainset, so you do as you see fit. I happen to think people who don't know what `.map` does are able to look it up, and easily understand it. They might even find it a pleasing idiom to use!

I'm baffled by your point about paths - the calling file (or "service worker") can only see things within its own scope. It makes no difference whether the path it is looking at came from an absolute or relative one. Are you assuming I didn't try this and ensure it actually functioned?

**Comment by chrisdavidmills** [comment]
> It's your trainset, so you do as you see fit. I happen to think people who don't know what .map does are able to look it up, and easily understand it. They might even find it a pleasing idiom to use!

Your thought here is not unreasonable, but I'd prefer to keep things simple here. The point is to teach PWAs, not map().


> I'm baffled by your point about paths - the calling file (or "service worker") can only see things within its own scope. It makes no difference whether the path it is looking at came from an absolute or relative one. Are you assuming I didn't try this and ensure it actually functioned?

Bah, seems I got a bit mixed up here, sorry about that. I just tried testing it again, and I can see that the changes you made inside the SW would indeed be fine. But I think I've still got a point about the path inside the register function in the main JS. I think this still has to be relative to the base URL. I got a 404 error when I did otherwise?

**Comment by mohawk2** [comment]
I didn't.

**Pull request closed without merging**
